### PR TITLE
Add CI script

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
This is failing on:

```
#=== ERROR while compiling fsevents-lwt.dev ===================================#
# context     2.0.5 | macos/x86_64 | ocaml-system.4.08.1 | pinned(file:///Users/travis/build/mirage/ocaml-fsevents)
# path        ~/.opam/ocaml-system/.opam-switch/build/fsevents-lwt.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p fsevents-lwt -j 1
# exit-code   1
# env-file    ~/.opam/log/fsevents-lwt-8577-05296d.env
# output-file ~/.opam/log/fsevents-lwt-8577-05296d.out
### output ###
# [...]
# (cd _build/default && /usr/local/bin/ocamlopt.opt -w -40 -g -o src/fs_events.exe -I /Users/travis/.opam/ocaml-system/lib/bytes -I /Users/travis/.opam/ocaml-system/lib/cf -I /Users/travis/.opam/ocaml-system/lib/cf-lwt -I /Users/travis/.opam/ocaml-system/lib/cmdliner -I /Users/travis/.opam/ocaml-system/lib/ctypes -I /Users/travis/.opam/ocaml-system/lib/fsevents -I /Users/travis/.opam/ocaml-syst[...]
# Undefined symbols for architecture x86_64:
#   "_ffi_closure_alloc", referenced from:
#       _ctypes_make_function_pointer in libctypes-foreign-base_stubs.a(ffi_call_stubs.o)
#   "_ffi_closure_free", referenced from:
#       _finalize_closure in libctypes-foreign-base_stubs.a(ffi_call_stubs.o)
#   "_ffi_prep_closure_loc", referenced from:
#       _ctypes_make_function_pointer in libctypes-foreign-base_stubs.a(ffi_call_stubs.o)
# ld: symbol(s) not found for architecture x86_64
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "caml_startup", line 1:
# Error: Error during linking
```

Which I have no idea how to fix properly...

**Comment by yallop** [comment]
That looks like a `libffi` version mismatch.

**Comment by samoht** [comment]
Indeed -- but it's not clear how to fix Travis :-)

**Comment by yallop** [comment]
The `ctypes` OS X Travis job [installs libffi from `brew`](https://github.com/ocamllabs/ocaml-ctypes/blob/7a5656807d54bdeefd2a17d5709b30864547b4bf/.travis-ci.sh#L32).  Can you do the same here?

**Comment by yallop** [comment]
Hmm: I see that you're already doing that.  I wonder if any of the discussion [here](https://github.com/ocamllabs/ocaml-ctypes/issues/74) will help.  If not, it might be worth looking more closely at the ctypes travis job spec.

**Comment by samoht** [comment]
I've tried to add a `brew update` to match with ctypes' CI is doing.

**Comment by avsm** [comment]
I'm considering fixing this with a vendored libffi on macos in the ctypes/dune port. It seems a heck of a lot easier to do that than to disambiguate multiple libffi's (including a system-installed one) otherwise :-/

**Comment by yallop** [comment]
Ideally we'd have a configuration script in `conf-libffi` (a.k.a. the `ctypes-foreign` package) to determine the location of the appropriate version of libffi-on-macos.

**Comment by samoht** [comment]
Merging this -- will try to improve the CI situation in subsequent work.

**Pull request merged**
